Fix up of bit library
unified-naming-convention/NamingStandard pull request #7
Opened 2022-05-09 01:49 UTC by jdpatdiscord

2022-05-09 03:08 UTC, ShowerHead-FluxTeam commented
I ShowerHeadFD, approve this request.

2022-05-09 05:03 UTC, LuaOranges requested changes

2022-05-09 22:17 UTC, jdpatdiscord commented on api/bit/bit.arshift.md
> +# bit.band
This file is now fixed up.

2022-05-09 22:17 UTC, jdpatdiscord commented on RuntimeCompliance.lua
> +for _, o in next, {"bit", "cache"} do
Removed the file. Will add it in the future

2022-05-16 17:37 UTC, LuaOranges commented
Looks good. As this is mostly just a cleanup PR I'll merge it now.

2022-05-16 17:37 UTC, merged